#!/bin/sh

MODDIR='/c/Projects/DAO/archid'

while getopts gs flag
do
  case "${flag}" in
    g) # Use alternative CFN stack, used for testing
     emvflags="${emvflags}g";;
    s) # Delete the stack and exit
     emvflags="${emvflags}s";;
  esac
done

echo "Moving toolset export files..."
[[ ! -z $emvflags ]] && emvflags="-${emvflags}"
./dao-emv ${emvflags}
echo "Processing GDA files ..."
./dao-gda

cd ${MODDIR}
echo "Removing toolset exported source files..."
rm -rf package_override/toolsetexport 2>/dev/null
rm addin/core/override/toolsetexport/* 2>/dev/null
rm addin/module/override/toolsetexport/* 2>/dev/null
rm ~/Documents/BioWare/Dragon\ Age/modules/Single\ Player/override/toolsetexport/* 2>/dev/null
echo
git add *
git status