#!/bin/sh

MODDIR='/c/Projects/DAO/archid'
echo "Moving toolset export files..."
./dao-emv
echo "Processing GDA files ..."
./dao-gda

cd ${MODDIR}
echo "Removing toolset exported source files..."
rm -rf package_override/toolsetexport 2>/dev/null
rm addin/core/override/toolsetexport/* 2>/dev/null
rm addin/module/override/toolsetexport/* 2>/dev/null
rm ~/Documents/BioWare/Dragon\ Age/modules/Single\ Player/override/toolsetexport/* 2>/dev/null
echo
git add *
git status