#!/bin/bash
rm -rf package_override/toolsetexport 2>/dev/null
rm addin/core/override/toolsetexport/* 2>/dev/null
rm addin/module/override/toolsetexport/* 2>/dev/null
rm ~/Documents/BioWare/Dragon\ Age/modules/Single\ Player/override/toolsetexport/* 2>/dev/null
