#!/bin/bash
rm -rf package_override/toolsetexport
rm addin/core/override/toolsetexport/*
rm addin/module/override/toolsetexport/*
rm ~/Documents/BioWare/Dragon\ Age/modules/Single\ Player/override/toolsetexport/*
